server:
  port: 2002
spring:
  application:
    name: hfpro
    id: hfpro-01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hfpro?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 3000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
logging:
  level:
    org:
  config: classpath:log4j2-spring.xml
  
mybatis:
  mapper-locations: classpath:com/hf/pro/mapper/*Mapper.xml
  config-location: classpath:mybatis.xml
  type-aliases-package: com.hf.pro